---
title: Inspect Viz Examples
format: 
   html: 
      code-tools: false
      page-layout: article
tbl-colwidths: [35,65]
---

These examples demonstrate various plotting and interactivity features. If you are just beginning to use Inspect Viz you review the [Getting Started](../index.qmd) article before exploring these examples.

## Inspect

These examples demonstrates creating visualisations from Inspect log files (leveraging the functions in [inspect_ai.analysis](https://inspect.aisi.org.uk/dataframe.html) module for creation of data frames from logs).

|  |  |
|------------------------------------|------------------------------------|
| [Scores by Task](inspect/scores-by-task/index.qmd) | Bar plot summarizing eval scores by model and task. |
| [Scores by Factor](inspect/scores-by-factor/index.qmd) | Bar plot for comparing eval scores by model and a boolean factor (e.g. no hint vs. hint). |
| [Scores by Model](inspect/scores-by-model/index.qmd) | Visualise model scores on a single evaluation, with one or more baselines. |
| [Scores by Limit](inspect/scores-by-limit/index.qmd) | Line plot for evaluating how a model’s success rate changes as token or time limits  increase.
| [Scores Timeline](inspect/scores-timeline/index.qmd) | Eval scores for various models, with release date on the x-axis. |
| [Scores Heatmap](inspect/scores-heatmap/index.qmd) |  Heatmap with values for comparing scores across model and task. |
| [Scores Radar](inspect/scores-radar/index.qmd) |  Radar plot to compare scores across models and metrics in a single eval. |
| [Sample Tool Calls](inspect/sample-tool-calls/index.qmd) | Visualise tool usage over a series of turns. |
| [Sample Heatmap](inspect/sample-heatmap/index.qmd) | a Heatmap for viewing individual sample scores. |


## General

These examples demonstrate general plotting techniques using a variety of other examples datasets.

|  |  |
|------------------------------------|------------------------------------|
| [Penguins Explorer](general/penguins/index.qmd) | Dot plots, tables, color and symbol channels, filtering inputs. |
| [Bias Parameter](general/bias-parameter/index.qmd) | Area plots; slider inputs; channel expressions. |
| [Seattle Weather](general/seattle-weather/index.qmd) | Dot plots; bar plots; color and radius channels; x-interval selections, interactive legend. |
| [Athletes (Regression)](general/athletes-regression/index.qmd) | Dot plots; regression lines; tables, filtering inputs, xy selections. |
| [Athletes (Error Bars)](general/athletes-errorbars/index.qmd) | Error bars; text annotations; params, slider inputs. |

