project:
   type: website
   pre-render: 
      - reference/filter/sidebar.py

metadata-files: 
  - reference/_sidebar.yml  

filters:
  - at: pre-quarto
    path: reference/filter/interlink.lua
 
website:
   title: "Inspect Viz"
   bread-crumbs: true
   page-navigation: true
   repo-url: https://github.com/meridianlabs-ai/inspect_viz
   site-url: https://meridianlabs-ai.github.io/inspect_viz
   repo-actions: [issue]
   navbar:
      title: "Inspect Viz"
      background: light
      search: true
      left:      
          - text: "Getting Started"
            href: index.qmd
          - text: "Concepts"
            href: concepts.qmd
          - text: "Reference"
            href: reference/index.qmd
          - text: "Examples"
            href: examples/index.qmd
          - text: "Sandbox"
            href: sandbox/index.qmd
      right: 
          - icon: github
            href: https://github.com/meridianlabs-ai/inspect_viz
      
   sidebar:
      - title: Examples
        style: docked
        contents:
          - href: examples/index.qmd
            text: Examples
          - href: examples/penguins/index.qmd
          - href: examples/bias-parameter/index.qmd
          - href: examples/seattle-weather/index.qmd
          - href: examples/athletes-regression/index.qmd
          - href: examples/athletes-errorbars/index.qmd
      - title: Sandbox
        style: docked
        contents:
          - href: sandbox/index.qmd
            text: Sandbox
          - href: sandbox/evals_summary.ipynb
          - href: sandbox/trajectory_analysis.ipynb
   page-footer: 
      left: 
         - text: Meridian Labs
           href: https://github.com/meridianlabs-ai/
      center: 
         - text: Code
           href: https://github.com/meridianlabs-ai/inspect_viz
         - text: License
           href: https://github.com/meridianlabs-ai/inspect_viz/blob/main/LICENSE 
         - text: Issues
           href: https://github.com/meridianlabs-ai/inspect_viz/issues
       
      right:
         - icon: github
           href: https://github.com/meridianlabs-ai/inspect_viz
           aria-label: Inspect on GitHub
      
format:
   html:
     theme: [cosmo, theme.scss]
     toc: true
     toc-depth: 3
     code-overflow: wrap
     code-annotations: select
     fig-width: 8
     fig-height: 4

execute: 
  daemon: false
