---
title: Output Format
tbl-colwidths: [30,70]
---

## Overview

By default, content generated by Inspect Viz is rendered as Jupyter Widgets that use JavaScript to provide various interactive features (tooltips, filtering, brushing, etc.). While this is the recommended way to publish Inspect Viz content, you can also choose to render content as static PNG images. 

You might want do this if you are creating an Office or PDF document or want your plots to be available even when disconnected from the Internet. Note however that rendering plots as PNG images does take longer than the native JavaScript output format, and that interactive features are not available in this mode.

## Prerequisites

To create PNG output with Inspect Viz, first install the [playwright](https://playwright.dev/python/) Python package, which enables taking screenshots of web graphics using an embedded version of the Chromium web browser. You can do this as follows:

``` bash
pip install playwright
playwright install
```

## Output Format 

Use the global `output_format` option to specify that you'd like to generate content in PNG format. For example, the plot below is rendered as a static PNG graphic:

```{python}
from inspect_viz import Data, options
from inspect_viz.view.beta import scores_by_factor

# set 'png' as default output format # <1>
options.output_format = "png"        # <1>

# render plot
evals = Data.from_file("evals-hint.parquet")
scores_by_factor(evals, "task_arg_hint", ("No hint", "Hint"))
```

1. Set the global `options.output_format` option to render all plots as static PNG images.

You can also do this for a single plot or set of plots using `options_context()`:

```python
from inspect_viz import options_context

with options_context(output_format="png"):
    # plot code here
```



