---
title: Dashboards
page-layout: full
---

## Overview

[Quarto Dashboards](https://quarto.org/docs/dashboards/) are a special type of Quarto website optimized for publishing easily navigable sets of plots and tables. Features of Quarto Dashboards include:

1. Many flexible ways to layout components (row or column based, tabsets, multiple pages, etc.) including responsive layout for mobile devices.

2. A variety of ways to present inputs for interactivity including toolbars, sidebars, and card-level inputs.

3. Dozens of available themes including the ability to create your own themes.

## Example

Here is the [Penguin Explorer](examples/penguins/index.qmd) example from this repository re-written as a dashboard (this is a live dashboard embedded as an iframe):

```{=html}
<iframe src="https://jja.quarto.pub/penguins-explorer/" style="width: 100%; height: 800px;" class="border column-body-outset-right"></iframe>
```

Below is the source code for this dashboard. You'll notice that this looks quite similar to the code for any other Quarto document, but level-two headings (`##`) have been added to denote a toolbar and dashboard rows (additional headings could be used to create columns and tabsets). 

````python
---
title: "Penguins Explorer"
format: dashboard # <1>
---

```{{python}}
from inspect_viz import Data, Param
from inspect_viz.input import select
from inspect_viz.mark import dot
from inspect_viz.plot import plot
from inspect_viz.table import table

penguins = Data.from_file("penguins.parquet")
axes = ["body_mass", "flipper_length", "bill_depth", "bill_length"]
x_axis = Param("body_mass")
y_axis = Param("flipper_length")
```

## Row {.toolbar} # <2>
 # <2>
```{{python}} # <2>
select(penguins, label="Species", column="species") # <2>
select(label="X", options=axes, target=x_axis) # <2>
select(label="Y", options=axes, target=y_axis) # <2>
``` # <2>

## Row # <3>

```{{python}}
plot(
    dot(penguins, x=x_axis, y=y_axis, stroke="species", symbol="species"),
    grid=True,
    x_label="Body mass (g) →",
    y_label="↑ Flipper length (mm)",
    legend="symbol",
)
``` # <3>

## Row

```{{python}}
table(penguins)
```
````

1. `format: dashboard` indicates this is a dashbaord not an ordinary HTML page.

2. Toolbar for grouping inputs.

3. Row sections to denote additional rows in the dashboard layout.

## Learning More

- See the [Quarto Dashboards](https://quarto.org/docs/dashboards/) documentation for additional details on creating dashboards.

- See the [Dashboard Examples](https://quarto.org/docs/gallery/#dashboards) to get an idea for the sorts of layouts and themes that are available and to see the source code for a variety of dashboard types.