---
title: "Sample Heatmap"
reference: "inspect_viz.view.beta"
filters: 
   - at: pre-ast
     type: json
     path: reference/filter/filter.py
   - at: pre-ast
     path: reference/filter/post.lua
datafile: "writing_bench_samples.parquet"
---

## Overview

The `sample_heatmap()`function renders a heatmap for viewing individual sample scores. Each sample is shown along one axis, models are shown along the other axis.

```{python}
from inspect_viz import Data
from inspect_viz.view.beta import sample_heatmap

samples = Data.from_file("writing_bench_samples.parquet")
sample_heatmap(
  samples, 
  score_value="score_multi_scorer_wrapper", 
  height=200
)
```

## Data Preparation

Above we read the data for the plot from a parquet file. This file was in turn created by:

1. Reading logs into a dataframe with `samples_df`, specifying the SampleSummaryColumns and the EvaalModel columns.

2. Using the `prepare()` function to `model_info()` and `log_viewer()` columns to the data frame.

```python
from inspect_ai.analysis import samples_df, log_viewer, model_info, prepare, EvalModel, SampleSummary

df = samples_df("logs", columns=SampleSummary + EvalModel)
df = prepare(df, [
    model_info(), 
    log_viewer("sample", {"logs": "https://samples.meridianlabs.ai/"})
  ])
df.to_parquet("writing_bench_samples.parquet")
```

If your samples are using non-numeric values (for example 'C' and 'I' to represent correct and incorrect), you can use the `score_to_float` prepare function in `inspect.analysis` to convert the score values to floats. For example:

```python
from inspect_ai.analysis import samples_df, log_viewer, model_info, score_to_float, prepare, EvalModel, SampleSummary

df = samples_df("logs", columns=SampleSummary + EvalModel)
df = prepare(df, [
    model_info(), 
    log_viewer("sample", {"logs": "https://samples.meridianlabs.ai/"}),
    score_to_float("score_includes")
  ])
```

{{< include _data_preparation_optional.md >}}


## Function Reference {reference="sample_heatmap"}

## Implementation

The [Sample Heatmap](examples/inspect/sample-heatmap/index.qmd) example demonstrates how this view was implemented using lower level plotting components.

