name: Publish Package

on:
    workflow_dispatch:
        inputs:
            target:
                description: 'Where to publish'
                required: true
                type: choice
                options:
                    - testpypi
                    - pypi
                    - both

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write # Required for OIDC/trusted publishing
        environment:
            name: ${{ inputs.target == 'pypi' && 'pypi' || 'testpypi' }}
            url: ${{ inputs.target == 'pypi' && 'https://pypi.org/p/inspect_viz' || 'https://test.pypi.org/p/inspect_viz' }}

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0 # Get all tags for version detection

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: '3.x'

            - name: Show current version
              run: |
                  echo "Version: $(git describe --tags --always)"

            - name: Build
              run: |
                  pip install --upgrade pip build
                  python -m build
                  ls -la dist/

            - name: Publish to TestPyPI
              if: inputs.target == 'testpypi' || inputs.target == 'both'
              uses: pypa/gh-action-pypi-publish@release/v1
              with:
                  repository-url: https://test.pypi.org/legacy/

            - name: Publish to PyPI
              if: inputs.target == 'pypi' || inputs.target == 'both'
              uses: pypa/gh-action-pypi-publish@release/v1
